config/routes.rb
require "monban/constraints/signed_in"

Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  constraints Monban::Constraints::SignedIn.new do
    get "/", to: "dashboards#show", as: :dashboards
    resources :users, only: [:show]
    resource :employer_options, only: [:show]
  end

  root to: "homes#show", via: :get
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :employer, inclusion: [true, false]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
  end
end

app/controllers/employer_options_controller.rb
class EmployerOptionsController < ApplicationController
  def show
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      flash.now.alert = "Invalid username or password"
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(
      :email,
      :password,
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_errors.html.erb
<% if @user.errors.any? %>
  <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
  <ul>
    <% @user.errors.full_messages.each do |error_message| %>
      <li><%= error_message %></li>
    <% end %>
  </ul>
<% end %>

app/views/dashboards/show.html.erb
<% if current_user.try(:employer) %>
  <%= link_to "Create a listing", employer_options_path %>
<% end %>
<style>
h3 {
  color: black;
}

div.panel-body {
  color: black;
}
</style>
<div class="container-full" style="background-image: url(assets/images/clouds.jpg);">
  <div class="row">
    <div class="col-lg-12 text-center v-center">
      <h1>Results</h1>
      <br><br><br>
    </div>
  </div>

  <div class="col-md-10 col-md-offset-1">
    <div class="list-group">
      <div class="list-group-item row">
        <div class="row">

          <div class="col-md-3 col-xs-3 text-center">
            <h3 style="color:black;">Company</h3>
          </div>

          <div class="col-md-3 col-xs-3 text-center">
            <h3>Job</h3>
          </div>

          <div class="col-md-3 col-xs-3 text-center">
            <h3>Skills</h3>
          </div>

          <div class="col-md-3 col-xs-3 text-center" style="padding-left:55px;">
            <h3>Rating</h3>
          </div>
        </div>
      </div>
      <! --  start of list item -->
      <br/><br/>

      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
          <div class="panel-heading" row="tab" id="headingFour">
            <div class="list-group-item row">

              <div class="col-md-3 col-xs-3 text-center">
                <span class="company logo">
                  <img alt src="assets/images/BostonGlobe.png" style="width:150px;height:60px">
                </span>
              </div>

              <div class="col-md-3 col-xs-3 text-center">
                <span class="company name">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne" class="collapsed">
                      Seeking Journalist with Marketing Mindset
                    </a>
                  </h4>

                </span>
              </div>

              <div class="col-md-3 col-xs-3 text-center">
                <span class="job skills">
                  <h6>
                    <span class="label label-primary">Writing Skills</span>
                    <br/>
                    <span class="label label-success"> Research</span>
                    <br/>
                    <span class="label label-info">PR/Outreach</span>
                  </h6>
                </span>
              </div>

              <div class="col-md-3 col-xs-3 text-center">
                <span class="rating">
                  <h4 text>
                    <span class="badge">94%</span>
                  </h4>
                </span>
              </div>
            </div>
          </div>

          <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
              Our client located in Downtown Boston is looking for a smart and driven journalist with a marketing mindset who wants to learn and earn at the same time. The ideal person has college journalism experience, and he or she is excited to learn more about content marketing. This is the perfect project for a smart and reliable experience seeker who is not only motivated to add vibrant pieces to their portfolio but who also wants to gain a load of transferrable soft skills. $400 for 4 weeks.
              <span="label label-success"><%= link_to "Apply", class: "btn btn-success" %></span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" row="tab" id="headingTwo">


        <div class="list-group-item row">

          <div class="col-md-3 col-xs-3 text-center">
            <span class="company logo">
              <img alt src="assets/images/buzzfeed_logo.png" style="width:90px;height:60px">
            </span>
          </div>

          <div class="col-md-3 col-xs-3 text-center">
            <span class="company name">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" class="collapsed">
                  Hilarious Comic Strip Writers
                </a>
              </h4>
            </span>
          </div>

          <div class="col-md-3 col-xs-3 text-center">
            <span class="job skills">
              <h6>
                <span class="label label-primary">Great Writing Skills</span>
                <br/>
                <span class="label label-success">Sense of Humor</span>
                <br/>
                <span class="label label-info">WordPress</span>
              </h6>
            </span>
          </div>

          <div class="col-md-3 col-xs-3 text-center">
            <span class="rating">
              <h4 text>
                <span class="badge">91%</span>
              </h4>
            </span>
          </div>
        </div>
      </div>
      <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
        <div class="panel-body">
          We're looking for between 10-20 jokes which will be whittled down to 6. These will accompany cartoons. $60 compensation.
          <span="label label-success"><%= link_to "Apply", class: "btn btn-success" %></span>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" row="tab" id="headingThree">

        <div class="list-group-item row">

          <div class="col-md-3 col-xs-3 text-center">
            <span class="company logo">
              <img alt src="assets/images/huffpo-logo.png" style="width:60px;height:60px">
            </span>
          </div>

          <div class="col-md-3 col-xs-3 text-center">
            <span class="company name">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree" class="collapsed">
                  Awesome Freelance Journalist (long-term)
                </a>
              </h4>
            </span>
          </div>

          <div class="col-md-3 col-xs-3 text-center">
            <span class="job skills">
              <h6>
                <span class="label label-primary">Industry Expertise</span>
                <br/>
                <span class="label label-success">Content Marketing</span>
                <br/>
                <span class="label label-info">Twitter</span>
              </h6>
            </span>
          </div>

          <div class="col-md-3 col-xs-3 text-center">
            <span class="rating">
              <h4 text>
                <span class="badge">89%</span>
              </h4>
            </span>
          </div>
        </div>
      </div>
      <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
        <div class="panel-body">
          Compensation 2k-5k DOE and quality of work and turnaround time.
          <span="label label-success"><%= link_to "Apply", class: "btn btn-success" %></span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employer_options/show.html.erb
<h1>Welcome <%= current_user.username %></h1>

app/views/homes/show.html.erb
<!-- Intro Header -->
<header class="intro">
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <img src="assets/images/logo_about.png" style="width:400px;height:173px" align="middle"> <br><br>
          <form class="col-lg-12">
            <div class="input-group" style="width:340px;text-align:center;margin:0 auto;">
              <input class="form-control input-lg" title="Enter desired skills you want to learn" placeholder="Start looking for an internship" type="text">
              <span class="input-group-btn"><button class="btn btn-lg btn-primary" style="background-color:white;" type="button"><%= link_to "Go!", new_session_path %></button></span>
            </div>
          </form><!-- About Section -->
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <p class="intro-text">Bringing the real world to the campus and bringing talented students into your workplace</p>
          <a href="#about" class="btn btn-circle page-scroll">
            <i class="fa fa-angle-double-down animated"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</header>
<section id="about" class="container content-section text-center">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h2>About Freelanship</h2>
      <p>Managing four classes and an internship was a daunting task in itself. Lauren knew it would be impossible to throw a part-time job into her already chaotic schedule; and so, she decided to create Freelanship, ” your internship alternative.” </p>
      <p>Internships are a vital part of the college experience but without support, the experience may be unfeasible. Although Lauren managed to get by, she realized many of her peers shared her dilemma.</p>
      <p>Now, both students and publications win through this mutually beneficial partnership known as <a href="http://Freelanship.com">Freelanship</a>.</p>
    </div>
  </div>
</section>

<!-- Contact Section -->
<section id="contact" class="container content-section text-center">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h2>Contact Information</h2>
      <p>We would love to hear your feedback, feel free to email us! </p>
      <p><a href="mailto:lah@freelanship.com">lah@freelanship.com</a>
      </p>

      <div class="row">

        <div class="col-lg-12 text-center v-center" style="font-size:39pt;">
          <a href="https://plus.google.com/112095273997718981060/posts"><i class="icon-google-plus"></i></a> <a href="https://www.facebook.com/Freelanship"><i class="icon-facebook"></i></a>  <a href="https://twitter.com/freelanship"><i class="icon-twitter"></i></a> <a href="https://www.linkedin.com/company/freelanship"><i class="icon-linkedin"></i></a> <a href="http://www.pinterest.com/holaur/freelanship-3/"><i class="icon-pinterest"></i></a>
        </div>

      </div>
    </div>
  </div>
</section>

<!-- Footer -->
<div class="row">
  <div class="col-lg-11">
    <p class="pull-right">Freelanship ©</p>
    <br><br>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freelanship</title>
    <!-- all metas -->
    <%= csrf_meta_tags %>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="generator" content="Bootply" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- all stylesheets -->
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">

    <!-- all javascripts -->
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  </head>
  <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
          <i class="fa fa-bars"></i>
        </button>
        <a class="navbar-brand page-scroll" href="#page-top">
          <i class="fa fa-play-circle"></i>  <span class="light"> <a href="#page-top"> <%= link_to "Start searching!", new_session_path %></a></span>
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
        <ul class="nav navbar-nav">
          <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
          <% if signed_in? %>
            <li><%= link_to "Sign out", session_path, method: :delete %></li>
          <% else %>
            <li class="hidden">
            <a href="#page-top"></a>
            </li>
            <li>
            <a class="page-scroll" href="#about">About</a>
            </li>
            <li>
            <a class="page-scroll" href="#contact">Contact</a>
            </li>
            <li><%= link_to "Sign Up", new_user_path %></li>
            <li><%= link_to "Sign In", new_session_path %></li>
          <% end %>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
    </nav>

    <% if alert %>
      <p><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <div>
    <%= render "errors", target: @user %>
  </div>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>